# Generated by Django 5.1.3 on 2024-11-18 13:14

import Student.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=Student.models.rename_file_student)),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=2)),
                ('standard', models.CharField(default=11, max_length=255)),
                ('start_year', models.CharField(max_length=4)),
                ('student_type', models.CharField(choices=[('Regular', 'Regular'), ('Only NEET/JEE', 'Only NEET/JEE'), ('Repeater', 'Repeater')], max_length=50)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('student_mobile_number', models.CharField(default=None, max_length=255)),
                ('parrent_mobile_number', models.CharField(default=None, max_length=255)),
                ('discussed_fee', models.IntegerField()),
                ('remaining_fees', models.IntegerField()),
                ('status', models.CharField(choices=[('Studying', 'Studying'), ('Not Studying', 'Not Studying'), ('Completed', 'Completed')], default='Studying', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('H', 'Holiday'), ('P', 'Present'), ('A', 'Absent')], default='A', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to=Student.models.rename_file_document)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
