# Generated by Django 5.1.3 on 2024-11-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
